version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build:
    docker:
      - image: circleci/python:2.7-node
    environment:
      AWS_REGION: us-east-2
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - aws-s3/sync:
          aws-access-key-id: AWS_KEY
          aws-secret-access-key: AWS_SECRET
          from: dist
          to: 's3://dev-ci-cd-laban/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master